import json
import os
training_data_list = [
    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nAI and Machine Learning (ML) are rapidly transforming risk assessment in banking. Traditional linear models often fail to capture complex, non-linear dependencies in market and credit data. ML algorithms, specifically neural networks and decision trees, provide superior predictive accuracy for default probability and fraud detection. The key challenge lies in model explainability (XAI) to satisfy regulators, as black-box models are unacceptable for critical financial decisions. Available Images: [IMAGE_FIN_F1: Neural network diagram, IMAGE_FIN_F2: Graph of market volatility, IMAGE_FIN_F3: Magnifying glass over compliance text",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":4,"presentation_title":"ML for Next-Gen Risk Modeling","presentation_subtitle":"Enhancing Predictive Accuracy in Credit and Fraud Detection","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Limitations of Linear Models","sub_heading":"Failure to Capture Non-Linear Financial Risk","bullet_points":["Traditional models miss complex dependencies.","Non-linear relationships define market volatility.","ML models offer superior predictive accuracy."],"speaker_notes":"Begin by contrasting old methods with the complexity of modern financial data. ML is a necessity.","image_concept":"Graph of market volatility","image_placeholder_id":"IMAGE_FIN_F2"},{"slide_number":2,"layout_type":"SECTION_HEADER","main_title":"Core ML Algorithms in Use","sub_heading":"Neural Networks and Advanced Decision Trees","bullet_points":[],"speaker_notes":"Highlight the specific ML models driving improvements in risk assessment.","image_concept":null,"image_placeholder_id":null},{"slide_number":3,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"The XAI Challenge","sub_heading":"Ensuring Model Explainability for Regulators","bullet_points":["Regulators demand full model transparency (XAI).","Black-box models are unacceptable for finance.","Explainability builds client and regulatory trust."],"speaker_notes":"This is the critical hurdle: performance vs. explainability. Discuss methods like LIME/SHAP.","image_concept":"Neural network diagram with highlighted path","image_placeholder_id":"IMAGE_FIN_F1"},{"slide_number":4,"layout_type":"CONCLUSION","main_title":"Conclusion: Next Steps","sub_heading":"Focus on Accuracy and Regulatory Compliance","bullet_points":["Adopt advanced, non-linear ML techniques.","Prioritize XAI frameworks for all models.","Ensure continuous regulatory compliance."],"speaker_notes":"Final takeaway emphasizes the balance between innovation and governance.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nThe core of a modern Search Engine Optimization (SEO) strategy centers on high-quality, long-form content that addresses user intent rather than simply keyword density. Search engines prioritize E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) signals, rewarding sites that demonstrate deep subject mastery. Technical SEO remains foundational, requiring fast site speed, mobile-friendliness, and a clean site architecture to ensure crawlability. The primary goal is to achieve featured snippets and high organic click-through rates (CTR). Available Images: [IMAGE_MKT_F1: E-E-A-T acronym graphic, IMAGE_MKT_F2: Mobile phone loading screen, IMAGE_MKT_F3: Pyramid representing site architecture]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":3,"presentation_title":"Modern SEO Strategy Essentials","presentation_subtitle":"Beyond Keywords: Focusing on E-E-A-T and User Intent","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Content Quality First","sub_heading":"Addressing Specific User Search Intent","bullet_points":["Content must be high-quality and long-form.","Focus on user intent, not keyword density.","Goal is to earn featured snippets and high CTR."],"speaker_notes":"SEO is now about satisfying the user entirely, not tricking the algorithm. Discuss semantic search.","image_concept":"Mobile phone loading screen for speed","image_placeholder_id":"IMAGE_MKT_F2"},{"slide_number":2,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"E-E-A-T Signals","sub_heading":"Building Authority and Trustworthiness for Ranking","bullet_points":["Search engines reward expertise and trust.","Demonstrate deep subject matter mastery.","Authority is a critical ranking factor."],"speaker_notes":"Explain the components of E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness).","image_concept":"E-E-A-T acronym graphic","image_placeholder_id":"IMAGE_MKT_F1"},{"slide_number":3,"layout_type":"CONCLUSION","main_title":"Technical Foundation","sub_heading":"Ensuring Site Speed and Crawlability","bullet_points":["Technical SEO is still the essential foundation.","Maintain fast site speed and mobile-friendliness.","Clean site architecture ensures full crawlability."],"speaker_notes":"End by stressing that good content fails without a solid technical base.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nEffective employee onboarding is a critical factor in retention and productivity. A well-structured program should extend beyond the first week, ideally spanning 90 days, to fully integrate new hires into the company culture and team structure. Key components include role clarity, administrative setup (IT access, paperwork), and mentorship pairing. Technology, specifically automated workflows, is essential for delivering personalized content and ensuring consistency across all departments, minimizing administrative burden on managers. Available Images: [IMAGE_HR_F1: Two people shaking hands over a desk, IMAGE_HR_F2: Digital checklist or flow chart, IMAGE_HR_F3: Team members collaborating at a whiteboard]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":4,"presentation_title":"Effective 90-Day Onboarding","presentation_subtitle":"Strategy for New Hire Retention and Productivity","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT","main_title":"Onboarding is Retention","sub_heading":"Extending the Program Beyond the First Week","bullet_points":["Onboarding impacts long-term employee retention.","Program should ideally span 90 days.","Full integration requires time and structure."],"speaker_notes":"Highlight the business case: a great onboarding program reduces turnover costs significantly.","image_concept":null,"image_placeholder_id":null},{"slide_number":2,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Core Program Components","sub_heading":"Clarity, Administration, and Mentorship","bullet_points":["Ensure absolute role clarity immediately.","Complete administrative and IT setup quickly.","Pairing with a mentor is highly valuable."],"speaker_notes":"Detail the three pillars: what the employee does, how they work, and who supports them.","image_concept":"Two people shaking hands over a desk","image_placeholder_id":"IMAGE_HR_F1"},{"slide_number":3,"layout_type":"TITLE_ONLY","main_title":"Leveraging Automation","sub_heading":"Delivering Personalized, Consistent Content","bullet_points":[],"speaker_notes":"Focus on how tech eliminates manual work and guarantees every employee receives the same high-quality experience.","image_concept":null,"image_placeholder_id":null},{"slide_number":4,"layout_type":"CONCLUSION","main_title":"Key Success Metric","sub_heading":"Reduced Time-to-Productivity (TTP)","bullet_points":["Successful onboarding cuts time-to-productivity.","It reduces administrative burden on managers.","Leads to better engagement and satisfaction."],"speaker_notes":"End with the quantifiable benefit (TTP) and a clear call to action on process improvement.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nThe core of the Zero Trust security model is the concept of 'never trust, always verify.' Unlike traditional perimeter security, Zero Trust assumes breach and requires strict verification for every user and device attempting to access network resources, regardless of location. Implementation relies on micro-segmentation, strong identity verification (IAM), and continuous monitoring. This shift is essential for defending against sophisticated insider threats and supply chain attacks. Available Images: [IMAGE_CYB_F1: Network map with micro-segments, IMAGE_CYB_F2: Lock icon with 'Verify' label]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":4,"presentation_title":"Implementing Zero Trust Security","presentation_subtitle":"Never Trust, Always Verify for Modern Defense","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT","main_title":"The Zero Trust Mandate","sub_heading":"Why Perimeter Security is No Longer Enough","bullet_points":["Zero Trust assumes the network is compromised.","Requires verification for all resources and users.","Essential for defense against insider threats."],"speaker_notes":"Explain the fundamental paradigm shift from network walls to identity verification.","image_concept":null,"image_placeholder_id":null},{"slide_number":2,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Core Principles","sub_heading":"Micro-Segmentation and Strong IAM","bullet_points":["Micro-segmentation limits lateral movement.","Strong Identity and Access Management is key.","Continuous monitoring tracks all network activity."],"speaker_notes":"Detail the three main technical components of a successful implementation plan.","image_concept":"Network map with micro-segments","image_placeholder_id":"IMAGE_CYB_F1"},{"slide_number":3,"layout_type":"TITLE_ONLY","main_title":"Benefits and Impact","sub_heading":"Defending Against Sophisticated Attacks","bullet_points":[],"speaker_notes":"Focus on how this model handles cloud environments and remote workers more securely.","image_concept":null,"image_placeholder_id":null},{"slide_number":4,"layout_type":"CONCLUSION","main_title":"Summary: Always Verify","sub_heading":"The Future of Enterprise Security","bullet_points":["Adopt ZTA to minimize breach impact.","Integrate strong IAM and segmentation tools.","Prioritize continuous, real-time verification."],"speaker_notes":"Final takeaway should emphasize the proactive nature of Zero Trust.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nThe successful launch of the new product, 'Project Nexus,' requires a phased Go-to-Market (GTM) strategy beginning with an Early Access Program (EAP) targeting high-value, existing clients. This initial phase validates product-market fit and collects critical performance feedback. Phase Two, the Public Beta, focuses on generating initial press coverage and optimizing conversion funnels. Key metrics are EAP participation rate, time-to-value, and customer acquisition cost (CAC) optimization. Available Images: [IMAGE_GTM_F1: Phased timeline chart, IMAGE_GTM_F2: Target symbol over a map]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":3,"presentation_title":"GTM for Project Nexus","presentation_subtitle":"Phased Approach to Launching New Product","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Phase One: Early Access","sub_heading":"Validating Fit with High-Value Clients","bullet_points":["Target high-value, existing clients for EAP.","Validate product-market fit rigorously.","Collect performance and feature feedback."],"speaker_notes":"Explain the strategic value of starting small to minimize risk before full public release.","image_concept":"Phased timeline chart","image_placeholder_id":"IMAGE_GTM_F1"},{"slide_number":2,"layout_type":"TITLE_AND_CONTENT","main_title":"Phase Two: Public Beta","sub_heading":"Optimizing Funnels and Generating Buzz","bullet_points":["Focus on generating initial press coverage.","Optimize the conversion and sales funnels.","Expand target audience for broader feedback."],"speaker_notes":"Discuss the transition from closed testing to market exposure and lead generation efforts.","image_concept":null,"image_placeholder_id":null},{"slide_number":3,"layout_type":"CONCLUSION","main_title":"Key Success Metrics","sub_heading":"Measuring Program Performance and Efficiency","bullet_points":["Track Early Access Participation Rate.","Monitor Time-to-Value (TTV) for all users.","Optimize Customer Acquisition Cost (CAC)."],"speaker_notes":"Conclude with a clear statement on how success will be measured financially and operationally.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to cnvert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nThe primary challenge in large-scale cloud migration is the '7 Rs' framework, specifically the complexity of 'Replatforming' and 'Refactoring' legacy monolithic applications. A phased, risk-averse approach is necessary, starting with low-risk workloads ('Rehost') to build expertise. Governance must be established upfront to manage cost overruns and ensure security compliance in the new environment. The ultimate goal is to enable agility and reduce operational expense. Available Images: [IMAGE_TECH1_F1: Cloud-shaped icon with arrows, IMAGE_TECH1_F2: Server room with old racks, IMAGE_TECH1_F3: Arrow pointing from Monolith to Microservices]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":4,"presentation_title":"Phased Cloud Migration","presentation_subtitle":"Strategy for Managing Legacy Applications and Costs","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"The 7 R Challenge","sub_heading":"Focusing on Refactoring and Replatforming Complexity","bullet_points":["Legacy systems require replatforming/refactoring.","Monolithic applications are the most difficult hurdle.","Start with low-risk Rehost to build expertise."],"speaker_notes":"Detail the 7 Rs framework and identify the most complex stages for large enterprises.","image_concept":"Arrow pointing from Monolith to Microservices","image_placeholder_id":"IMAGE_TECH1_F3"},{"slide_number":2,"layout_type":"SECTION_HEADER","main_title":"Governance and Cost Control","sub_heading":"Establishing Security and Budget Oversight","bullet_points":[],"speaker_notes":"Stress the need for clear financial tracking and adherence to security policies from day one in the cloud.","image_concept":null,"image_placeholder_id":null},{"slide_number":3,"layout_type":"TITLE_AND_CONTENT","main_title":"Enabling Business Agility","sub_heading":"The Strategic Benefit of Cloud Adoption","bullet_points":["Cloud infrastructure enables business agility.","Reduces overall operational expense (OpEx).","Allows faster feature deployment and scaling."],"speaker_notes":"Shift the focus from technical challenge to the strategic business value derived from the move.","image_concept":null,"image_placeholder_id":null},{"slide_number":4,"layout_type":"CONCLUSION","main_title":"Key Migration Takeaways","sub_heading":"Phased Approach, Governance, and Agility","bullet_points":["Prioritize a phased, risk-averse rollout.","Implement strict governance for cost management.","Measure success by agility and cost reduction."],"speaker_notes":"Final summary of the process and the desired end-state benefits.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nThe transition from monolithic to microservices architecture is driven by the need for independent deployment and technology flexibility. Each service runs in its own process and communicates via lightweight mechanisms, typically APIs. This independence improves resilience and accelerates development velocity. However, it introduces significant complexity in managing distributed transactions and requires robust observability tools for monitoring and debugging across multiple services. Available Images: [IMAGE_TECH2_F1: Interconnected services/nodes, IMAGE_TECH2_F2: Magnifying glass over code, IMAGE_TECH2_F3: Developer working on code]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":3,"presentation_title":"Microservices Architecture","presentation_subtitle":"Benefits and Challenges of Distributed Systems","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Why Microservices?","sub_heading":"Driving Independent Deployment and Resilience","bullet_points":["Enables independent deployment of services.","Increases technological flexibility and choice.","Improves system resilience and scalability."],"speaker_notes":"Focus on the core benefits: faster deployments and the ability to scale components individually.","image_concept":"Interconnected services/nodes","image_placeholder_id":"IMAGE_TECH2_F1"},{"slide_number":2,"layout_type":"TITLE_AND_CONTENT","main_title":"New Operational Challenges","sub_heading":"Managing Distributed Transactions and Observability","bullet_points":["Introduces complexity in distributed transactions.","Requires robust, centralized observability tools.","Debugging spans multiple independent services."],"speaker_notes":"Detail the necessary tooling and process changes needed for successful distributed system management.","image_concept":null,"image_placeholder_id":null},{"slide_number":3,"layout_type":"CONCLUSION","main_title":"Summary: Accelerating Velocity","sub_heading":"Achieving Speed Through Service Independence","bullet_points":["Prioritize service independence for velocity.","Invest heavily in observability and monitoring.","Standardize API communication across the board."],"speaker_notes":"Conclude with the overall gain in development speed and operational independence.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nDevSecOps embeds security practices throughout the entire software development lifecycle (SDLC), shifting the focus from late-stage auditing to continuous, automated checks. Key practices include using static and dynamic application security testing (SAST/DAST) tools within the CI/CD pipeline and implementing automated infrastructure-as-code (IaC) security scans. This continuous integration of security minimizes vulnerabilities and dramatically reduces the cost of fixing defects found early. Available Images: [IMAGE_TECH3_F1: Infinity loop with 'Security' added, IMAGE_TECH3_F2: Shield icon over code, IMAGE_TECH3_F3: Developer and security analyst collaborating]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":5,"presentation_title":"Implementing DevSecOps","presentation_subtitle":"Embedding Security in the Continuous Delivery Pipeline","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Shift Left Security","sub_heading":"Integrating Checks Throughout the SDLC","bullet_points":["Security is embedded across the entire SDLC.","Shifts focus from late auditing to early checks.","Reduces the cost of fixing vulnerabilities."],"speaker_notes":"Explain the Shift Left concept and its financial benefits for defect remediation.","image_concept":"Infinity loop with Security added","image_placeholder_id":"IMAGE_TECH3_F1"},{"slide_number":2,"layout_type":"SECTION_HEADER","main_title":"CI/CD Automation","sub_heading":"Leveraging SAST and DAST Tools","bullet_points":[],"speaker_notes":"Highlight the role of automated tools like SAST/DAST in maintaining pipeline speed while enforcing security.","image_concept":null,"image_placeholder_id":null},{"slide_number":3,"layout_type":"TITLE_AND_CONTENT","main_title":"Securing Infrastructure","sub_heading":"Automated Scanning of Infrastructure-as-Code","bullet_points":["Automated scans validate IaC configuration.","Prevents security drift in cloud environments.","Ensures consistent security baseline."],"speaker_notes":"Discuss how tools like Terraform or Ansible scripts should be scanned before deployment.","image_concept":null,"image_placeholder_id":null},{"slide_number":4,"layout_type":"TITLE_ONLY","main_title":"Cultural Transformation","sub_heading":"Collaboration Between Teams is Essential","bullet_points":[],"speaker_notes":"Mention the human element: security must become a shared responsibility, not just an audit function.","image_concept":null,"image_placeholder_id":null},{"slide_number":5,"layout_type":"CONCLUSION","main_title":"Final DevSecOps Summary","sub_heading":"Continuous, Automated, and Collaborative Security","bullet_points":["Automate security testing in all stages.","Treat Infrastructure as Code as critical.","Foster collaboration between Dev and Security."],"speaker_notes":"Final takeaway focusing on the three pillars of a successful DevSecOps implementation.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nChoosing the right Agile framework is crucial for team success. Scrum is defined by time-boxed iterations (sprints) and specific roles (Scrum Master, Product Owner), making it ideal for projects with frequent changes and tight deadlines. Kanban, on the other hand, is a continuous flow system focused on limiting Work in Progress (WIP) to optimize flow and is better suited for maintenance or operations teams where work arrives unpredictably. Both prioritize rapid feedback and continuous improvement. Available Images: [IMAGE_TECH4_F1: Scrum team in a meeting, IMAGE_TECH4_F2: Kanban board with WIP limits, IMAGE_TECH4_F3: Time clock icon]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":3,"presentation_title":"Choosing Your Agile Path","presentation_subtitle":"Scrum vs. Kanban for Project Success","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Scrum: Time-Boxed Iterations","sub_heading":"Best for Projects with Frequent Change","bullet_points":["Defined by fixed, time-boxed sprints.","Requires specific, defined team roles.","Ideal for product development and change."],"speaker_notes":"Explain Scrums rigidity (sprints) is its strength for complex, time-sensitive projects.","image_concept":"Scrum team in a meeting","image_placeholder_id":"IMAGE_TECH4_F1"},{"slide_number":2,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Kanban: Continuous Flow","sub_heading":"Optimizing Flow and Limiting Work in Progress","bullet_points":["Focuses on continuous flow, no fixed sprints.","Key metric is limiting Work in Progress (WIP).","Better for operational or maintenance teams."],"speaker_notes":"Contrast this with Kanban, which is event-driven and optimizes for efficiency rather than planning.","image_concept":"Kanban board with WIP limits","image_placeholder_id":"IMAGE_TECH4_F2"},{"slide_number":3,"layout_type":"CONCLUSION","main_title":"Agile Core Principles","sub_heading":"Prioritizing Feedback and Improvement","bullet_points":["Both prioritize rapid feedback mechanisms.","Both drive continuous process improvement.","The choice depends on workflow predictability."],"speaker_notes":"Final takeaway should emphasize that the underlying agile values are more important than the specific framework.","image_concept":null,"image_placeholder_id":null}]}' 
    },

    {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nThe primary challenge in large-scale cloud migration is the 7 Rs framework, specifically the complexity of 'Replatforming' and 'Refactoring' legacy monolithic applications. A phased, risk-averse approach is necessary, starting with low-risk workloads ('Rehost') to build expertise. Governance must be established upfront to manage cost overruns and ensure security compliance in the new environment. The ultimate goal is to enable agility and reduce operational expense. Available Images: [IMAGE_TECH1_F1: Cloud-shaped icon with arrows, IMAGE_TECH1_F2: Server room with old racks, IMAGE_TECH1_F3: Arrow pointing from Monolith to Microservices]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":4,"presentation_title":"Phased Cloud Migration","presentation_subtitle":"Strategy for Managing Legacy Applications and Costs","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"The 7 Rs Challenge","sub_heading":"Focusing on Refactoring and Replatforming Complexity","bullet_points":["Legacy systems require replatforming/refactoring.","Monolithic applications are the most difficult hurdle.","Start with low-risk Rehost to build expertise."],"speaker_notes":"Detail the 7 Rs framework and identify the most complex stages for large enterprises.","image_concept":"Arrow pointing from Monolith to Microservices","image_placeholder_id":"IMAGE_TECH1_F3"},{"slide_number":2,"layout_type":"SECTION_HEADER","main_title":"Governance and Cost Control","sub_heading":"Establishing Security and Budget Oversight","bullet_points":[],"speaker_notes":"Stress the need for clear financial tracking and adherence to security policies from day one in the cloud.","image_concept":null,"image_placeholder_id":null},{"slide_number":3,"layout_type":"TITLE_AND_CONTENT","main_title":"Enabling Business Agility","sub_heading":"The Strategic Benefit of Cloud Adoption","bullet_points":["Cloud infrastructure enables business agility.","Reduces overall operational expense (OpEx).","Allows faster feature deployment and scaling."],"speaker_notes":"Shift the focus from technical challenge to the strategic business value derived from the move.","image_concept":null,"image_placeholder_id":null},{"slide_number":4,"layout_type":"CONCLUSION","main_title":"Key Migration Takeaways","sub_heading":"Phased Approach, Governance, and Agility","bullet_points":["Prioritize a phased, risk-averse rollout.","Implement strict governance for cost management.","Measure success by agility and cost reduction."],"speaker_notes":"Final summary of the process and the desired end-state benefits.","image_concept":null,"image_placeholder_id":null}]}' 
    },

     {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nThe pharmaceutical drug discovery pipeline is a multi-stage process starting with target identification and validation, followed by lead compound identification through high-throughput screening (HTS). The most critical and resource-intensive phase is preclinical testing, which assesses drug efficacy and safety in animal models before moving to human clinical trials. Failure rates remain high, especially between Phase I and Phase II trials. Utilizing AI for virtual screening and toxicity prediction is accelerating the initial stages. Available Images: [IMAGE_RES1_F1: Drug discovery pipeline chart, IMAGE_RES1_F2: Flasks in a laboratory, IMAGE_RES1_F3: Computer model of a protein]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":4,"presentation_title":"Drug Discovery Pipeline","presentation_subtitle":"Identifying Targets to Clinical Trials","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Multi-Stage Process","sub_heading":"From Target ID to Preclinical Testing","bullet_points":["Starts with target identification and validation.","Lead compounds found via high-throughput screening.","Preclinical phase assesses efficacy and safety."],"speaker_notes":"Outline the sequential, high-risk nature of the R&D process and the financial investment required.","image_concept":"Drug discovery pipeline chart","image_placeholder_id":"IMAGE_RES1_F1"},{"slide_number":2,"layout_type":"SECTION_HEADER","main_title":"The Clinical Hurdle","sub_heading":"Navigating High Failure Rates in Human Trials","bullet_points":[],"speaker_notes":"Focus on the high attrition rate, particularly the transition from a successful Phase I to Phase II.","image_concept":null,"image_placeholder_id":null},{"slide_number":3,"layout_type":"TITLE_AND_CONTENT","main_title":"AI Acceleration","sub_heading":"Virtual Screening and Toxicity Prediction","bullet_points":["AI accelerates early-stage drug discovery.","Virtual screening identifies better lead compounds.","Toxicity prediction reduces costly failures later."],"speaker_notes":"Introduce modern techniques that are streamlining the initial, resource-intensive phase.","image_concept":null,"image_placeholder_id":null},{"slide_number":4,"layout_type":"CONCLUSION","main_title":"Conclusion: Risk Management","sub_heading":"Leveraging AI to Improve Discovery Efficiency","bullet_points":["Focus resources on target validation early on.","Utilize AI for predictive screening and toxicity.","Manage high financial risk in clinical phases."],"speaker_notes":"Final takeaway should emphasize efficiency gains through technology adoption.","image_concept":null,"image_placeholder_id":null}]}' 
    },

     {
        "instruction": "You are a highly analytical Presentation Architect. Your sole task is to convert the provided document excerpt and image list into a structured, multi-slide JSON presentation outline. Return ONLY the JSON object. Do not include any explanations, markdown fences (like `json`), or commentary. The output must strictly adhere to the provided schema and its explicit constraints (e.g., word limits, total_slides, ENUM values).",
        "input": "---INPUT TEXT---\n\nSolid-state battery technology is poised to revolutionize electric vehicles and energy storage due to its potential for higher energy density and improved safety compared to traditional liquid lithium-ion batteries. Replacing the liquid electrolyte with a solid ceramic or polymer eliminates the risk of thermal runaway and fire. Key research challenges include achieving stable, high-conductivity solid electrolytes and minimizing the interfacial resistance between the electrolyte and electrodes. Available Images: [IMAGE_RES2_F1: Diagram of solid-state vs. liquid-ion battery, IMAGE_RES2_F2: Electric vehicle charging, IMAGE_RES2_F3: Material science diagram of ceramic structure]",
        # NOTE: The 'output' value here should be the MINIFIED JSON string
        "output": '{"total_slides":3,"presentation_title":"Solid-State Batteries","presentation_subtitle":"The Next Generation of Energy Storage","slides":[{"slide_number":1,"layout_type":"TITLE_AND_CONTENT_WITH_IMAGE","main_title":"Safety and Density Gains","sub_heading":"Overcoming Liquid Lithium-Ion Limitations","bullet_points":["Offers significantly higher energy density.","Improved safety eliminates thermal runaway risk.","Uses solid ceramic or polymer electrolyte."],"speaker_notes":"Introduce the technology and its two main advantages: more power in less space, and dramatically improved safety.","image_concept":"Diagram of solid-state vs. liquid-ion battery structure","image_placeholder_id":"IMAGE_RES2_F1"},{"slide_number":2,"layout_type":"TITLE_AND_CONTENT","main_title":"Key Research Challenges","sub_heading":"Addressing Conductivity and Resistance Issues","bullet_points":["Achieving high-conductivity solid electrolytes.","Minimizing interfacial resistance is a hurdle.","Scaling production remains technically difficult."],"speaker_notes":"Detail the primary material science and engineering obstacles that require further R&D investment.","image_concept":null,"image_placeholder_id":null},{"slide_number":3,"layout_type":"CONCLUSION","main_title":"Impact on EV and Grid","sub_heading":"Enabling Faster Charging and Longer Range","bullet_points":["Critical for longer range electric vehicles (EVs).","Essential for reliable grid-scale energy storage.","Requires continued materials science investment."],"speaker_notes":"Conclude with the broad market application and the necessity of ongoing research to commercialize the technology.","image_concept":null,"image_placeholder_id":null}]}' 
    }
]

output_filename = "training_data.jsonl"

def create_jsonl_file(data_list, filename):
    """Writes the list of training dictionaries to a JSON Lines file."""
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            for item in data_list:
                # Ensure the 'output' is a valid, minified JSON string
                # We need to use json.dumps again to ensure the nested string is escaped properly
                
                # NOTE: We assume the 'output' field is currently a Python string 
                # containing the minified JSON. If it's a python dict, you'd need one extra step.
                
                # We will re-format the data to ensure the structure is clean for the trainer
                # The final dictionary to dump to JSONL
                jsonl_entry = {
                    "instruction": item["instruction"],
                    "input": item["input"],
                    "output": item["output"] # This is the minified JSON string
                }
                
                f.write(json.dumps(jsonl_entry, ensure_ascii=False) + '\n')
        
        print(f"\n✅ Successfully created {len(data_list)} samples in {filename}.")
        print(f"File size: {os.path.getsize(filename) / 1024:.2f} KB.")

    except Exception as e:
        print(f"An error occurred during file creation: {e}")

# Assuming training_data_list is available in the current context
create_jsonl_file(training_data_list, output_filename)